"""
Persisted run transcript.

Writes a markdown record of one orchestrator.run() call once it's over —
goal, target, every tool call with its exact params/output (this vault's
writeups and Sherlock notes both require verbatim command/output blocks,
not paraphrases — see Tooling and Scripts/Techniques Index.md and the
Sherlocks pipeline conventions in CLAUDE.md; this follows the same rule),
and whatever report_finding calls were made along the way.

Where it goes:
  - If a target_name was given (this is a known HTB/lab box, passed via
    main.py's --target-name), writes to this vault's own
    Recon Output/Machines/<target_name>-dual-llm-run-<timestamp>.md — the
    same location recon-agent's raw notes go, so this harness's output
    sits next to the real pipeline's for that target instead of off in
    its own island. Recon Output/ is gitignored by default (see the vault
    .gitignore's "Recon output / lab-specific (private repo territory)"
    block), so this is private the same as recon-agent's own notes — no
    extra handling needed here.
  - Otherwise (a bare IP, an OffSec lab, anything without a tracked box
    name), writes to this harness's own ./runs/ directory instead, which
    stays entirely local to this folder and out of the vault's structure.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

# security-vault/Tooling and Scripts/dual-llm-orchestrator/notes.py
#   parents[0] = dual-llm-orchestrator, [1] = "Tooling and Scripts", [2] = security-vault
_VAULT_ROOT = Path(__file__).resolve().parents[2]


def write_run_transcript(
    *,
    target_host: str,
    target_name: str | None,
    goal: str,
    transcript: list[dict],
    findings: list[dict],
    cumulative_cost_usd: float = 0.0,
) -> Path:
    """Write the run's transcript to disk and return the path written."""
    now = _dt.datetime.now(_dt.timezone.utc)
    timestamp = now.strftime("%Y-%m-%dT%H%M%SZ")

    if target_name:
        out_dir = _VAULT_ROOT / "Recon Output" / "Machines"
        filename = f"{target_name}-dual-llm-run-{timestamp}.md"
    else:
        out_dir = Path(__file__).resolve().parent / "runs"
        filename = f"{target_host}-{timestamp}.md"

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / filename
    out_path.write_text(
        _render(target_host, target_name, goal, transcript, findings, now, cumulative_cost_usd)
    )
    return out_path


def _render(
    target_host: str,
    target_name: str | None,
    goal: str,
    transcript: list[dict],
    findings: list[dict],
    generated_at: _dt.datetime,
    cumulative_cost_usd: float = 0.0,
) -> str:
    lines = [
        f"# Dual-LLM orchestrator run — {target_name or target_host}",
        "",
        f"**Target:** {target_host}" + (f" ({target_name})" if target_name else ""),
        f"**Goal:** {goal}",
        f"**Generated:** {generated_at.isoformat()}",
        f"**Estimated Claude API cost this run:** ${cumulative_cost_usd:.4f} "
        f"(rough estimate from `response.usage` at list price — see "
        f"orchestrator.py's `_track_usage` docstring for what this does "
        f"and doesn't account for)",
        "",
        "Auto-generated by `Tooling and Scripts/dual-llm-orchestrator` — "
        "Claude as planner, a local model as CLI-syntax translator. This "
        "is a raw run transcript, not a reviewed writeup: verify each step "
        "before treating anything here as confirmed rather than attempted. "
        "See that folder's README.md for the pipeline this came from.",
        "",
    ]

    if findings:
        lines.append("## Findings")
        lines.append("")
        for f in findings:
            lines.append(f"### {f['finding_type']}")
            lines.append(f"- **Content:** {f['content']}")
            lines.append(f"- **Evidence:** `{f['evidence']}`")
            if f.get("session_id"):
                lines.append(f"- **Session:** {f['session_id']}")
            lines.append("")

    lines.append("## Transcript")
    lines.append("")
    for entry in transcript:
        if entry["kind"] == "text":
            lines.append(f"**[planner]** {entry['text']}")
            lines.append("")
        elif entry["kind"] == "tool_call":
            lines.append(f"### `{entry['tool']}`")
            lines.append("")
            lines.append("Params:")
            lines.append("```")
            lines.append(str(entry["params"]))
            lines.append("```")
            lines.append("")
            lines.append("Output:")
            lines.append("```")
            lines.append(str(entry["result"]))
            lines.append("```")
            lines.append("")

    return "\n".join(lines)
